// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0tpfIR99lUyLKFj9d-jhDIA79WJnSXTU',
    appId: '1:30159744418:web:52e93c8775d4e8d9f7d6fb',
    messagingSenderId: '30159744418',
    projectId: 'smart-dustbin-539ee',
    authDomain: 'smart-dustbin-539ee.firebaseapp.com',
    databaseURL: 'https://smart-dustbin-539ee-default-rtdb.firebaseio.com',
    storageBucket: 'smart-dustbin-539ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt27zrAPbFweDWMUKTsfkT1j_oyxwCFPo',
    appId: '1:30159744418:android:97c53d9712d2bcb1f7d6fb',
    messagingSenderId: '30159744418',
    projectId: 'smart-dustbin-539ee',
    databaseURL: 'https://smart-dustbin-539ee-default-rtdb.firebaseio.com',
    storageBucket: 'smart-dustbin-539ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRnfjdghJG3tp0oQwql6704XFLxi2DEhc',
    appId: '1:30159744418:ios:2b3da33b309a481cf7d6fb',
    messagingSenderId: '30159744418',
    projectId: 'smart-dustbin-539ee',
    databaseURL: 'https://smart-dustbin-539ee-default-rtdb.firebaseio.com',
    storageBucket: 'smart-dustbin-539ee.appspot.com',
    iosBundleId: 'com.example.smartDustbin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRnfjdghJG3tp0oQwql6704XFLxi2DEhc',
    appId: '1:30159744418:ios:2b3da33b309a481cf7d6fb',
    messagingSenderId: '30159744418',
    projectId: 'smart-dustbin-539ee',
    databaseURL: 'https://smart-dustbin-539ee-default-rtdb.firebaseio.com',
    storageBucket: 'smart-dustbin-539ee.appspot.com',
    iosBundleId: 'com.example.smartDustbin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0tpfIR99lUyLKFj9d-jhDIA79WJnSXTU',
    appId: '1:30159744418:web:752eabcf8a2d0b63f7d6fb',
    messagingSenderId: '30159744418',
    projectId: 'smart-dustbin-539ee',
    authDomain: 'smart-dustbin-539ee.firebaseapp.com',
    databaseURL: 'https://smart-dustbin-539ee-default-rtdb.firebaseio.com',
    storageBucket: 'smart-dustbin-539ee.appspot.com',
  );

}